# Generated by Django 3.2.19 on 2026-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20260207_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='For Vercel: Paste external image URL here instead of uploading (e.g., from Imgur, Cloudinary)', null=True),
        ),
    ]
